### ISSUE TITLE
Management Exception invalid class

### ISSUE THREAD

**Issue by tbeattie63** [MatthewKing/DeviceId#81] opened 2023-11-13 06:02 UTC
Using DeviceId 6.4.0, Device.Windows.Wmi 6.5.0

Possibly caused by locked down permissions on corporate network.

at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__95`1.MoveNext()
   at DeviceId.Windows.Wmi.Components.WmiSystemDriveSerialNumberDeviceIdComponent.GetValue()
   at DeviceId.Formatters.HashDeviceIdFormatter.<>c.<GetDeviceId>b__4_1(KeyValuePair`2 x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DeviceId.Formatters.HashDeviceIdFormatter.GetDeviceId(IDictionary`2 components)

**Comment by IsThatUniqueEnough** [comment] 2024-02-22 09:52
Exact same issue here. I think if getting the drive serial number (or any other id) can fail, the component should return null.

**Comment by MatthewKing** [comment] 2024-02-22 11:03
Thank you both for the report. This will be fixed in the next release. This project doesn't currently have the resources to diagnose environment-specific permissions issues, so instead I'm just going to catch any exceptions here and have the component return null.

If you need the fix earlier than next release, you can just copy+paste the contents of the updated `MmiSystemDriveSerialNumberDeviceIdComponent.cs` file into your own project, give it a new name, and add it using the `DeviceIdBuilder.AddComponent`

**Closed as completed by MatthewKing** 2024-02-22 11:03 UTC

**Comment by IsThatUniqueEnough** [comment] 2024-02-22 11:31
Thanks. That's fine for me - my workaround was to wrap the existing component in an own one simply catching the exception.

In my case the problem happened on a standalone machine. Probably caused by a consumer security suite or a corrupted WMI. Wasn't able to investigate that further and the workaround did the job.
